### ISSUE TITLE
Release sensor monitor

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/userapps#109]
[from here](https://www.dropbox.com/s/hoadb73fdyah02c/Post-O3%20task.xlsx?dl=0)

gw-vis/kagra-vis#16 : How do we connect the relase sensor to the binary input.

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-82) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
@Ryutaro-T @vis-ikeda これってインストール時しか使わないやつですか？池田さんにお願いしてデジタルシステムでモニターできるようにする必要がありますか？

**Comment by Ryutaro-T** [comment]
常にモニターできるようにする必要があります。

**Comment by vis-ikeda** [comment]
@Ryutaro-T @MiyoKouseki いつまでに必要か含めて具体的な内容をどこかで教えてください。

**Comment by MiyoKouseki** [comment]
リリースセンサーをどうDGSに繋ぐかを別のIssueで議論し始めているのですが、これはどうすればいいでしょうか。手作りはしたくないので、AELの方にお願いしたいのですが、これがどれぐらいの優先度でいつまでに欲しいのか明らかにしておきたいです。

**Comment by MiyoKouseki** [comment]
EYのインストール作業で用意できれば良いが、ローカルで回路ボックスに繋いで確認する方が便利なので、特にこの時までに必要ということではない。

インストール後で良いと思う。来年4月とかで。

**Comment by MiyoKouseki** [comment]
https://dacgit.icrr.u-tokyo.ac.jp/issues/546?issue_count=37&issue_position=2&next_issue_id=541&prev_issue_id=547

に移動
