### ISSUE TITLE
Functions are not properly distributed in 'main' and 'run'

### ISSUE THREAD

**Issue by AyakaAShoda** [gw-vis/userapps#13]
Some functions are in 'run,' and continuously turning off the switch. The log goes away and it makes it difficult to investigate the issue.

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-20) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
Close
