### ISSUE TITLE
'all_off_quick' function does not working properly.

### ISSUE THREAD

**Issue by AyakaAShoda** [gw-vis/userapps#14]
Some filters, such as IM_OLDAMP_L, TM_DITHER does not turned off.

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-19) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
I don't the button well. I think we don't use in the current system anymore. So I close it.
