### ISSUE TITLE
Write a manual for the limit switch installation

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/userapps#162]
インストールマニュアルを書く。

https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=11520

- [x] どこに何をインストールするか、情報を共有。
- [ ] Hardware 部分のインストールマニュアルを書く
- [x] Software 部分のインストールマニュアルを書く
- [x] インストール後の動作確認項目とその確認方法を書く
- Done

**Comment by vis-ikeda** [comment]
**Software 部分のインストールマニュアルを書く**
Limit switchの確認方法
ソフトウエアインストール手順（TBD）も併せて記載
正式版はハードウエアのインストール手順と相談してから決める予定
[Limit switch connecting guide_rev.2.pptx](https://github.com/gw-vis/userapps/files/5296342/Limit.switch.connecting.guide_rev.2.pptx)

**Comment by vis-ikeda** [comment]
**どこに何をインストールするか、情報を共有。**

satoさん、takahashiさん＞
　ハードウエアのインストール日程と順番について情報を共有したい。
　現状リミットスイッチの対応について
　ソフトウエアとしてはGASは試験環境で確認しているが、
　IP側は未確認なので最初はソフトウエアの試験を兼ねてのインストール作業になるものと考えております。
　その為、VISのインストールの日程について認識をあせておきたいと考えております。

**Comment by MiyoKouseki** [comment]
@vis-ikeda @NaohisaSato @Ryutaro-T @で通知を飛ばせるので是非。

**Comment by vis-ikeda** [comment]
・インストール後の動作確認項目とその確認方法を書く
#164にて記載

**Comment by vis-ikeda** [comment]
・どこに何をインストールするか、情報を共有。
　今回Limit SwitchがInstallされるのはType-A, Type-BのIPより上が対象
　Type-Aは既にInstallされているものもあるがソフトウエアからみて同じなので問題なし。
　L-Rが入れ替わっている可能性があるのでチェックが必要とのこと。

**Comment by MiyoKouseki** [comment]
もう、準備完了ですか？

**Comment by vis-ikeda** [comment]
ソフトウエアはインストール方法が変更になったので自動でできない(LVDTを見ながらStepperを動かしてstepperの上限下限位置を探す)
MEDM追加と書き直しが必要な認識。

**Comment by vis-ikeda** [comment]
Stepper用のMEDM [OVERVIEW]を新規作成
sitemapの[STEPPING MOTOR]から呼び出せるように変更、
今までの[STEP_MASTER]と[OVERVIEW]を選べるように変更しました。

これに伴いSoftware Installマニュアルを書き換えました。
[Limit switch connecting guide.pptx](https://github.com/gw-vis/userapps/files/5456543/Limit.switch.connecting.guide.pptx)

**Comment by MiyoKouseki** [comment]
ありがとうございます。
Reviewに移動できますか？

**Comment by vis-ikeda** [comment]
@NaohisaSato さんがまだ修正するとのことです。

**Comment by NaohisaSato** [comment]
@MiyoKouseki , @vis-ikeda 修正終わりました。

**Comment by MiyoKouseki** [comment]
ありがとうございます。Closeします。
