### ISSUE TITLE
Make OFFLOAD mini

### ISSUE THREAD

**Issue by vis-ikeda** [gw-vis/userapps#179]

**Comment by vis-ikeda** [comment]
MEDM画面作成

![Screenshot_offload_mini.png](https://images.zenhubusercontent.com/5f59c326ef4c1e08d7a0bc2b/d480fbe1-49c2-48c2-a6e5-7380f4a11f89)

記憶している内にOFFLOAD_OVERVIEWのStatusのみ表示するモジュールを作成。
まだ[gw-vis/pcas-controller](https://github.com/gw-vis/pcas-controller/commit/0b56973d3d60c9bf815359677614a5adf10a352f)のGitにのみ、userapps配下には格納していない。
どこから使用するかはまた次回考える。

**Comment by MiyoKouseki** [comment]
Reviewに移動してもらえますか？

**Comment by MiyoKouseki** [comment]
ありがとうございます。Closeします。
