### ISSUE TITLE
To allow the script(step_start) to start and end on the screen.

### ISSUE THREAD

**Issue by vis-ikeda** [gw-vis/userapps#186]

**Comment by vis-ikeda** [comment]
xterm -e "ssh controls@k1script 'source /kagra/apps/etc/client-user-env.sh && step_start XXX' &"
にてスクリプト呼び出しができるのでこちらで実装してuserappsへ格納

**Comment by MiyoKouseki** [comment]
Closeできますか？できるならReviewに移動してもらえますか？

**Comment by vis-ikeda** [comment]
Closeできます。既にReview/QAですね。

**Comment by MiyoKouseki** [comment]
Ikeda-san made a button to start and stop the stepper script from OFFLOAD_OVERVIEW.adl.
