### ISSUE TITLE
IYC to vacuum(Nov. 20,2020)

### ISSUE THREAD

**Issue by vis-ikeda** [gw-vis/userapps#196]
・IYCの真空引きは2020/11/20午後から実施予定とのこと。
   詳細はまた連絡あり。今回は休日中も行われる。

・VISのOFFLOAD_OVERVIEWの監視は、
　11/20定時までは@vis-ikeda が実施
　以降は@Ryutaro-T さんが間欠で実施予定とのこと。

・今回は最初はあまり触らずどれくらい傾くか確認したいとのこと。
　OFFLOAD画面でERROR SIGが±5,000くらいまでは放置する。
　±5,000に近づきそうならば0方向へ戻す方針で進める。
　（通常は±300で補正している）

**Comment by vis-ikeda** [comment]
[追加情報]
11/20 15:00くらいから排気スタート予定
11/21は@MiyoKouseki さんがモニター予定

**Comment by vis-ikeda** [comment]
[CRY+VIS Interface Meeting 2020/11/20]より
・IYCは、今日クローズまでいくが想定よりも時間がかかっており早くても１７時くらいになる為、
　明日11/21の朝からポンピングスタートに変更したいとのこと。
  11/21朝に@MiyoKouseki さんへCRY側から連絡してから開始するとのこと。

**Comment by MiyoKouseki** [comment]
これは完了しました。
http://klog.icrr.u-tokyo.ac.jp/osl/?r=15513
