### ISSUE TITLE
Made VIS_OVERVIEW.adl

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/userapps#23]
aaa

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-10) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
![image](https://user-images.githubusercontent.com/24282734/90579238-62948780-e200-11ea-8074-ce2160cf5f57.png)

**Comment by AyakaAShoda** [comment]
I have deleted the link to commish messages screen and add the link to this VIS_OVERVIEW.adl in VIS_ALL.adl in order to avoid the confusion.

**Comment by MiyoKouseki** [comment]
Made.

Done.
