### ISSUE TITLE
Make the new directory structure

### ISSUE THREAD

**Issue by AyakaAShoda** [gw-vis/userapps#49]
In userapps? Please move if wrong.

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-8) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
I think this issue is resolved in  #53 .
Does anyone have other problem about the directory structure?
If you have, we make a new issue for it.

Wait for review.

**Comment by MiyoKouseki** [comment]
Done
