### ISSUE TITLE
Create a new structure of the measurement directory

### ISSUE THREAD

**Issue by AyakaAShoda** [gw-vis/userapps#53]
We have to make **a rule** for the measurement to avoid messy directory structure.
**Rule**

* The data is managed with the templates in principle. (#54 )
* Independent measurements should be stored in other places. Please store the personal directory you have.

## Todo
* [x] Prepare the directory for the templates and its results
* [ ] Done

## Review
Make a consensus in VIS people.

┆Issue is synchronized with this [Jira タスク](https://kagra-vis-software.atlassian.net/browse/UO4-4) by [Unito](https://www.unito.io/learn-more)

**Comment by MiyoKouseki** [comment]
Shoda-san's comment;

> If stored, they will be moved to a 'trash' directory.
> Idea of the structure idea below Dropbox/Measurements:
> SUS--- ETMX
>         |-- ETMY
>         |-- ...
>         |-- SR2
>         |-- ...
>         |-- PR2
>         |--...
>         |-- script
> 
>

**Comment by MiyoKouseki** [comment]
Currently, Yamamoto-san has prepared the directory for KAGRA people in ```/kagra/Dropbox/Measurements``` based on the above rule. So, It's done.

**Comment by MiyoKouseki** [comment]
Wait for review.

**Comment by MiyoKouseki** [comment]
relate to #49 
done
